### ISSUE TITLE
Should xdebug remote_autostart be 1?

### ISSUE THREAD

**Issue by tekante** [phase2/docker-apache-php-base#5]
I believe we may have some people depending on this configuration (and it doesn't appear to actively harm anything) but with this setting xdebug is always attempting to activate whether someone has requested to start a debugging session or not.

This makes configuration of the IDE simpler (someone doesn't have to fire up a debugging session, they just need to kick PHPStorm or other into "listen for debugging connections" mode). It may even make command line drush debugging simpler as well. At the cost of them not really understanding how they are interacting with xdebug and what they did to initiate that interaction.

**Comment by grayside** [comment]
Since the setting would only load if the PHP_XDEBUG environment variable is "true", this won't affect production. Making Xdebug a little easier seems worthwhile.

**Comment by tekante** [comment]
Seems reasonable to default to making stuff as easy to use as possible. Also, given subsequent testing of the build container we don't have a variables_order setting by default which would even support an on-demand initiation of xdeubg. Closing this out.
